/**
 * Created by AnhVTT on 6/8/2021.
 */
const GUIConst = {};

// Z Orders:
GUIConst.NOT_SHOWING_GUI_ZORDER = 98;

GUIConst.TOP_PANEL_ZORDER = 99;
GUIConst.GUI_ZORDER = 100;
GUIConst.GUI_BOSS_RUN_SAGA = 100;
GUIConst.GUI_BOSS_RUN_WELCOME = 101;
GUIConst.GUI_SHOP = 101;
GUIConst.TUT_FOG = 101;
GUIConst.SHOP_POPUP = 102;
GUIConst.TUT_BUBBLE_ZORDER = 102;
GUIConst.GUI_KING_CUP = 103;
GUIConst.GUI_SKY_RACE = 104;
GUIConst.GUI_EVENT_LAUNCHING = 105;
GUIConst.CLAIM_REWARD_ZORDER = 200;
GUIConst.GUI_ALERT_ZORDER = 200;
GUIConst.GUI_GLOBAL_GOLD_G_ZORDER = 300;
GUIConst.EFFECT_ZORDER = 1000;

// Sizes:
GUIConst.IOS_NOTCH_HEIGHT = 60;

// Colors:
GUIConst.TEXT_COLOR = {
    BROWN: cc.color(175,72,52),
    GREEN: cc.color(49,138,0)
};
